name: Generate Contribution Snake 🐍

on:
  schedule:
    - cron: "0 12 * * *"  # Una vez al día a las 12:00 UTC
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Snake animations
        uses: Platane/snk@v3
        with:
          github_user_name: SebastianMartinezLesmes
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            dist/github-contribution-grid-snake-ocean.gif?color_snake=%2300FFFF&color_dots=%230d1117,%23003366,%230055aa,%230077ff,%2300aaff

      - name: Push generated files
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: dist
          force_orphan: true
